module.exports =
	"US": "United States"
	"AL": "Albania"
	"DZ": "Algeria"
	"AD": "Andorra"
	"AO": "Angola"
	"AI": "Anguilla"
	"AG": "Antigua and Barbuda"
	"AM": "Armenia"
	"AZ": "Azerbaijan Republic"
	"AD": "Andorra"
	"AI": "Anguilla"
	"AR": "Argentina"
	"AW": "Aruba"
	"AU": "Australia"
	"AT": "Austria"
	"BS": "Bahamas"
	"BH": "Bahrain"
	"BB": "Barbados"
	"BE": "Belgium"
	"BZ": "Belize"
	"BJ": "Benin"
	"BM": "Bermuda"
	"BT": "Bhutan"
	"BO": "Bolivia"
	"BA": "Bosnia and Herzegovina"
	"BW": "Botswana"
	"BR": "Brazil"
	"VG": "British Virgin Islands"
	"BN": "Brunei"
	"BG": "Bulgaria"
	"BF": "Burkina Faso"
	"BI": "Burundi"
	"KH": "Cambodia"
	"CA": "Canada"
	"CV": "Cape Verde"
	"KY": "Cayman Islands"
	"TD": "Chad"
	"CL": "Chile"
	"C2": "China"
	"CR": "Costa Rica"
	"CO": "Colombia"
	"KM": "Comoros"
	"CK": "Cook Islands"
	"HR": "Croatia"
	"CY": "Cyprus"
	"CZ": "Czech Republic"
	"DK": "Denmark"
	"CD": "Democratic Republic of the Congo"
	"DJ": "Djibouti"
	"DM": "Dominica"
	"DO": "Dominican Republic"
	"EC": "Ecuador"
	"SV": "El Salvador"
	"ER": "Eritrea"
	"EE": "Estonia"
	"ET": "Ethiopia"
	"FK": "Falkland Islands"
	"FO": "Faroe Islands"
	"FM": "Federated States of Micronesia"
	"FJ": "Fiji"
	"FI": "Finland"
	"FR": "France"
	"GF": "French Guiana"
	"PF": "French Polynesia"
	"GA": "Gabon Republic"
	"GM": "Gambia"
	"DE": "Germany"
	"GI": "Gibraltar"
	"GR": "Greece"
	"GL": "Greenland"
	"GD": "Grenada"
	"GP": "Guadeloupe"
	"GT": "Guatemala"
	"GN": "Guinea"
	"GW": "Guinea Bissau"
	"GY": "Guyana"
	"HN": "Honduras"
	"HK": "Hong Kong"
	"HU": "Hungary"
	"IS": "Iceland"
	"IN": "India"
	"ID": "Indonesia"
	"IE": "Ireland"
	"IL": "Israel"
	"IT": "Italy"
	"JM": "Jamaica"
	"JP": "Japan"
	"JO": "Jordan"
	"KZ": "Kazakhstan"
	"KE": "Kenya"
	"KI": "Kiribati"
	"KW": "Kuwait"
	"KG": "Kyrgyzstan"
	"LA": "Laos"
	"LV": "Latvia"
	"LS": "Lesotho"
	"LI": "Liechtenstein"
	"LT": "Lithuania"
	"LU": "Luxembourg"
	"MG": "Madagascar"
	"MW": "Malawi"
	"MY": "Malaysia"
	"MV": "Maldives"
	"ML": "Mali"
	"MT": "Malta"
	"MH": "Marshall Islands"
	"MQ": "Martinique"
	"MR": "Mauritania"
	"MU": "Mauritius"
	"YT": "Mayotte"
	"MX": "Mexico"
	"MN": "Mongolia"
	"MS": "Montserrat"
	"MA": "Moroccoupdate"
	"MZ": "Mozambique"
	"NA": "Namibia"
	"NR": "Nauru"
	"NP": "Nepal"
	"NL": "Netherlands"
	"AN": "Netherlands Antilles"
	"NC": "New Caledonia"
	"NZ": "New Zealand"
	"NI": "Nicaragua"
	"NE": "Niger"
	"NU": "Niue"
	"NF": "Norfolk Island"
	"NO": "Norway"
	"OM": "Oman"
	"PW": "Palau"
	"PA": "Panama"
	"PG": "Papua New Guinea"
	"PE": "Peru"
	"PH": "Philippines"
	"PN": "Pitcairn Islands"
	"PL": "Poland"
	"PT": "Portugal"
	"QA": "Qatar"
	"CG": "Republic of the Congo"
	"RE": "Reunion"
	"RO": "Romania"
	"RU": "Russia"
	"RW": "Rwanda"
	"VC": "Saint Vincent and the Grenadines"
	"WS": "Samoa"
	"SM": "San Marino"
	"ST": "São Tomé and Príncipe"
	"SA": "Saudi Arabia"
	"SN": "Senegal"
	"SC": "Seychelles"
	"SL": "Sierra Leone"
	"SG": "Singapore"
	"SI": "Slovenia"
	"SB": "Solomon Islands"
	"SO": "Somalia"
	"ZA": "South Africa"
	"KR": "South Korea"
	"ES": "Spain"
	"LK": "Sri Lanka"
	"SH": "St. Helena"
	"KN": "St. Kitts and Nevis"
	"LC": "St. Lucia"
	"PM": "St. Pierre and Miquelon"
	"SR": "Suriname"
	"SJ": "Svalbard and Jan Mayen Islands"
	"SZ": "Swaziland"
	"SE": "Sweden"
	"CH": "Switzerland"
	"TJ": "Tajikistan"
	"TW": "Taiwan"
	"TZ": "Tanzania"
	"TH": "Thailand"
	"TG": "Togo"
	"TO": "Tonga"
	"TT": "Trinidad and Tobago"
	"TN": "Tunisia"
	"TR": "Turkey"
	"TM": "Turkmenistan"
	"TC": "Turks and Caicos Islands"
	"TV": "Tuvalu"
	"UG": "Uganda"
	"UA": "Ukraine"
	"AE": "United Arab Emirates"
	"GB": "United Kingdom"
	"US": "United States"
	"UY": "Uruguay"
	"VU": "Vanuatu"
	"VA": "Vatican City State"
	"VE": "Venezuela"
	"VN": "Vietnam"
	"WF": "Wallis and Futuna Islands"
	"YE": "Yemen"
	"ZM": "Zambia"
